"""Build the one-screen dashboard used for the walkthrough recording.

This is not a jeval command and not a product surface: the product writes one report, and a
dashboard is explicitly out of scope. This is a *presentation* of the same analysis, computed by the
same library, arranged so that one screen makes one argument -- the line in use is in the wrong
place, here is where it belongs, here is what moving it buys.

    uv run python examples/make-demo-dashboard.py examples/demo-dashboard.html

One file, no server, no network, no chart library, no JavaScript. Every figure is computed by the
library the report uses (``evaluate``, ``sweep_actions``, ``build_impact``), and nothing on the page
is typed in by hand, which is what makes it safe to put on screen.

The synthetic log is two model versions of the same four questions. The older version is roughly
honest on the question the cost matrix fires on; the newer one is degraded, which is the change the
drift check exists to catch.
"""

from __future__ import annotations

import sys
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jeval.cli import resolve_cost_actions, sweep_actions
from jeval.currency import format_amount
from jeval.drift import parse_fail_on, run_checks
from jeval.evaluate import DatasetReport, evaluate
from jeval.report import svg as S
from jeval.report.model import ImpactTable, ThresholdResult
from jeval.schema import DecisionRecord
from jeval.synth import SynthSpec, demo_dataset, generate

NEWER_START = datetime(2026, 9, 17, tzinfo=timezone.utc)

CURRENCY = "KRW"
MONTHLY_VOLUME = 20_000.0
CURRENT_THRESHOLD = 0.60
FAIL_ON = "ece-increase=0.05"

# The cost matrix the dashboard runs on -- the same synthetic one `jeval demo` writes, so the numbers
# on the screen can be checked against `examples/report-example.html` in this repository.
COSTS_YAML = """\
# SYNTHETIC cost figures. Replace them with your own before believing any threshold that comes
# out of this file.
actions:
  - name: auto_refund
    question: intent
    when: refund_request
    cost_false_accept: 12000
    cost_escalate: 2000
    cost_false_reject: 0
  - name: auto_route
    question: department
    when: billing
    cost_false_accept: 8000
    cost_escalate: 1500
    cost_false_reject: 200
  - name: auto_escalate_urgent
    question: is_urgent
    when: "yes"
    cost_false_accept: 30000
    cost_escalate: 500
    cost_false_reject: 1000
"""

# The chart is drawn at the column's width, so one viewBox unit is one CSS pixel on a laptop window
# and a 13px label is rendered at 13px instead of being scaled down.
COLUMN_W = 960.0
CHART_W = COLUMN_W
CHART_H = 372.0
PLOT_LEFT = 70.0
PLOT_RIGHT = 20.0
PLOT_TOP = 30.0
PLOT_BOTTOM = 140.0
STRIP_GAP = 24.0
STRIP_H = 58.0
LABEL_Y = 18.0
X_TICK_Y = 337.0
X_TITLE_Y = 358.0
Y_TITLE_X = 14.0


@dataclass
class Screen:
    """Everything the one screen shows, computed once."""

    dataset: DatasetReport
    result: ThresholdResult
    impact: ImpactTable
    metrics: Any
    failures: list[Any]
    question: str
    question_label: str


def build_records() -> tuple[list[DecisionRecord], list[DecisionRecord]]:
    """The version in production, and the candidate that has to be judged against it.

    The production half is `jeval demo`'s own log at the same seed, so the numbers on the screen can
    be checked against the committed report in this repository. The candidate is the same four
    questions generated by a degraded model: overconfident on the question the cost matrix fires on,
    which is the change the drift check exists to catch.
    """
    serving = list(demo_dataset(seed=11, scale=0.5).records)
    degraded = (
        SynthSpec(
            n=310,
            mode="overconfident",
            exponent=0.35,
            question_key="department",
            model="jev-1.14.0",
            start=NEWER_START,
            seed=21,
            languages=("ko", "en"),
            tiers=("free", "pro"),
            label_fraction=0.86,
        ),
        SynthSpec(
            n=270,
            mode="inflated",
            inflation=1.3,
            question_key="intent",
            classes=("refund_request", "check_balance", "other"),
            model="jev-1.14.0",
            start=NEWER_START,
            seed=22,
            languages=("ko", "en"),
            label_fraction=0.9,
        ),
        SynthSpec(
            n=215,
            mode="calibrated",
            question_key="is_urgent",
            question_type="noul",
            model="jev-1.14.0",
            start=NEWER_START,
            seed=23,
            languages=("ko", "en"),
            label_fraction=0.88,
        ),
        SynthSpec(
            n=110,
            mode="inflated",
            question_key="satisfaction",
            question_type="score",
            score_bias=0.18,
            model="jev-1.14.0",
            start=NEWER_START,
            seed=24,
            languages=("ko", "en"),
            label_fraction=0.8,
        ),
    )
    candidate = [record for spec in degraded for record in generate(spec)]
    return serving, candidate


def analyse(
    serving: Sequence[DecisionRecord], candidate: Sequence[DecisionRecord], costs_path: Path
) -> Screen:
    """Run the analysis the report runs, and keep the pieces one screen needs.

    The screen measures the version in production: a rollout decision is "here is what is live, here
    is what is proposed", and mixing the candidate into the reliability numbers would hide which of
    the two is miscalibrated. The candidate appears once, as the drift check's failure.
    """
    records = list(serving)
    dataset = evaluate(records, n_bins=10, alpha=0.05, n_boot=200, by=("lang", "tier"))
    actions, _note = resolve_cost_actions(costs_path, costs_path.parent)
    thresholds, impacts = sweep_actions(
        actions,
        records,
        n_boot=200,
        alpha=0.05,
        monthly_volume=MONTHLY_VOLUME,
        currency=CURRENCY,
        current_threshold=CURRENT_THRESHOLD,
    )
    result = next((item for item in thresholds if item.curve), None)
    assert result is not None, "the demo cost matrix must produce a sweep"
    question = next(
        (item for item in dataset.questions if item.question_key == result.question), None
    )
    metrics = question.metrics if question is not None else dataset.overall
    drift = _drift_view([*records, *candidate])
    failures = list(run_checks(drift, parse_fail_on((FAIL_ON,)))) if drift is not None else []
    return Screen(
        dataset=dataset,
        result=result,
        impact=impacts[result.action],
        metrics=metrics,
        failures=failures,
        question=result.question,
        question_label=result.action,
    )


def _drift_view(records: Sequence[DecisionRecord], *, min_slice: int = 30) -> Any:
    """Compare model versions when the log holds more than one."""
    if len({record.model for record in records}) < 2:
        return None
    from jeval import drift as drift_engine

    return drift_engine.compare(records, min_slice=min_slice, alpha=0.05, n_boot=200)


# --------------------------------------------------------------------------------------
# The chart
# --------------------------------------------------------------------------------------
# Drawn here rather than taken from `jeval.report.charts`, because this chart has to do something the
# report's does not: put both thresholds on one axis, label them where they stand, and show the
# confidence distribution underneath, so the reader can see what moves when the line moves.
# Colours come from CSS classes rather than attributes, so the chart follows the colour scheme.
def _threshold_line(
    x: float,
    *,
    y0: float,
    y1: float,
    label: str,
    anchor: str,
    line_cls: str,
    label_cls: str,
    dash: str = "",
) -> str:
    """A vertical line where a threshold sits, labelled where it sits.

    Both lines on this chart are labelled in words as well as drawn in different colours and dash
    patterns: a reader who cannot tell the colours apart still gets the whole argument.
    """
    return "".join(
        (
            S.line(x, y0, x, y1, dash=dash, cls=line_cls),
            S.text(
                x + (-10 if anchor == "end" else 10),
                LABEL_Y,
                label,
                anchor=anchor,
                size=13,
                weight=600,
                cls=label_cls,
                halo=True,
            ),
        )
    )


def _chart(screen: Screen) -> str:
    points = [point for point in screen.result.curve if point.expected_cost == point.expected_cost]
    assert points, "the sweep must produce points"
    costs = [point.expected_cost for point in points]
    lo, hi = min(costs), max(costs)
    pad = max(1e-9, (hi - lo) * 0.18)
    y_lo, y_hi = max(0.0, lo - pad), hi + pad

    x0, x1 = PLOT_LEFT, CHART_W - PLOT_RIGHT
    y_top = PLOT_TOP
    y_bottom = CHART_H - PLOT_BOTTOM
    strip_top = y_bottom + STRIP_GAP
    strip_bottom = strip_top + STRIP_H

    def px(threshold: float) -> float:
        return x0 + threshold * (x1 - x0)

    def py(cost: float) -> float:
        return y_bottom - (cost - y_lo) / max(1e-12, y_hi - y_lo) * (y_bottom - y_top)

    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    belongs = screen.result.threshold
    per_case = screen.result.expected_cost_per_case
    at_current = screen.result.point_at(current)
    currency = screen.impact.currency
    # The sweep is flat until it has a case it could move: below the lowest confidence the model
    # handles alone, raising the line changes nothing. Unannotated, that plateau reads as a
    # rendering fault -- its step lands exactly on the "in use" line -- so the chart says what it is.
    plateau = points[0].expected_cost
    plateau_end = max(
        (point.threshold for point in points if abs(point.expected_cost - plateau) < 1e-9),
        default=0.0,
    )

    parts = [
        S.svg_open(
            CHART_W,
            CHART_H,
            title=(
                "Expected cost per case against the threshold, with the line in use and the line "
                "the cost minimum points at"
            ),
            desc=(
                f"Cost per case is lowest at threshold {S.fmt(belongs)}, where it is "
                f"{format_amount(per_case, currency)}, and higher at the {S.fmt(current)} currently "
                "in use. The "
                "bars below the curve show how many decisions sit in each confidence range."
            ),
            cls="hero",
        )
    ]

    # The bootstrap interval on the threshold, drawn and not only printed: a point estimate quoted
    # over a wide interval is the easiest thing on this page to over-read.
    ci_low, ci_high = screen.result.ci_low, screen.result.ci_high
    if ci_high > ci_low:
        parts.append(
            S.rect(
                px(ci_low),
                y_top,
                px(ci_high) - px(ci_low),
                strip_bottom - y_top,
                cls="ci-band",
                extra=' stroke="none"',
            )
        )

    # Few gridlines: horizontal only, at round costs. The x axis gets tick marks, not a lattice.
    y_ticks = S.nice_ticks(y_lo, y_hi, target=4)
    y_label = S.tick_format(y_ticks)
    for value in y_ticks:
        y = py(value)
        parts.append(S.line(x0, y, x1, y, cls="grid"))
        parts.append(S.text(x0 - 10, y + 4, y_label(value), anchor="end", size=11.5, cls="tick"))
    for value in (0.0, 0.25, 0.5, 0.75, 1.0):
        x = px(value)
        parts.append(S.line(x, strip_bottom, x, strip_bottom + 6, cls="axis"))
        parts.append(S.text(x, X_TICK_Y, S.fmt(value), anchor="middle", size=11.5, cls="tick"))
    parts.append(S.line(x0, y_bottom, x1, y_bottom, cls="baseline"))
    parts.append(S.line(x0, strip_bottom, x1, strip_bottom, cls="axis"))
    parts.append(
        S.text(
            (x0 + x1) / 2.0,
            X_TITLE_Y,
            "threshold: how sure the model has to be before it answers alone",
            anchor="middle",
            size=12,
            weight=500,
            cls="label",
        )
    )
    parts.append(
        S.text(
            Y_TITLE_X,
            (y_top + y_bottom) / 2.0,
            f"cost per case ({currency})",
            anchor="middle",
            size=12,
            weight=500,
            cls="label",
            rotate=-90,
            rotate_at=(Y_TITLE_X, (y_top + y_bottom) / 2.0),
        )
    )

    # The distribution under the curve: how many decisions sit in each confidence band.
    buckets = list(screen.metrics.confidence_buckets)
    if buckets:
        peak = max(count for _lo, _hi, count in buckets) or 1
        for band_lo, band_hi, count in buckets:
            left = px(band_lo) + 1.0
            width = max(1.0, px(band_hi) - px(band_lo) - 2.0)
            height = max(1.0, (count / peak) * STRIP_H)
            parts.append(
                S.rect(
                    left,
                    strip_bottom - height,
                    width,
                    height,
                    cls="dist",
                    extra=' stroke="none"',
                )
            )
        # Every occupied band carries its count: with one band holding most of the decisions, the
        # other bars are a few pixels tall, and the number is what makes them readable.
        for band_lo, band_hi, count in buckets:
            if count:
                height = (count / peak) * STRIP_H
                parts.append(
                    S.text(
                        (px(band_lo) + px(band_hi)) / 2.0,
                        strip_bottom - height - 4,
                        f"{count:,}",
                        anchor="middle",
                        size=11.5,
                        cls="tick",
                    )
                )
        parts.append(
            S.text(
                x0,
                strip_top - 9,
                f"{screen.metrics.n:,} labeled decisions in these bands",
                size=12,
                cls="note",
            )
        )
        # The strip has its own unit, so it gets its own axis label; without one, bar heights read
        # as cost levels.
        parts.append(
            S.text(x0 - 10, strip_top + 12, "decisions", anchor="end", size=11.5, cls="tick")
        )

    parts.append(
        S.polyline(
            [(px(point.threshold), py(point.expected_cost)) for point in points],
            cls="curve",
            smooth=True,
        )
    )
    # Say why the left half of the curve is flat, using the threshold the plateau actually ends at.
    if plateau_end >= 0.2:
        parts.append(
            S.text(
                x0 + 10,
                py(plateau) + 18,
                f"flat to {S.fmt(plateau_end)}: every case the model would handle alone already "
                "sits above the line",
                size=12,
                cls="note",
                halo=True,
            )
        )
    # Direct labels on the two points that matter, so the reader never has to trace to an axis.
    if at_current is not None:
        y_now = py(at_current.expected_cost)
        parts.append(S.dot(px(current), y_now, 4.0, cls="inuse-dot", extra=' stroke="none"'))
        parts.append(
            S.text(
                px(current) - 12,
                y_now - 10,
                f"{format_amount(at_current.expected_cost, currency)} per case",
                anchor="end",
                size=12.5,
                weight=600,
                cls="inuse-value",
                halo=True,
            )
        )
    parts.append(
        S.dot(
            px(belongs),
            py(per_case),
            4.5,
            cls="min-dot",
            tooltip=f"cost minimum at {S.fmt(belongs)}",
            extra=' stroke="none"',
        )
    )
    parts.append(
        S.text(
            px(belongs) + 10,
            py(per_case) + 18,
            f"{format_amount(per_case, currency)} per case",
            size=12.5,
            weight=600,
            cls="belongs-value",
            halo=True,
        )
    )
    parts.append(
        _threshold_line(
            px(current),
            y0=y_top,
            y1=strip_bottom,
            label=f"in use {S.fmt(current)}",
            anchor="end",
            line_cls="inuse-line",
            label_cls="inuse-label",
            dash="5 4",
        )
    )
    parts.append(
        _threshold_line(
            px(belongs),
            y0=y_top,
            y1=strip_bottom,
            label=f"where it belongs {S.fmt(belongs)}",
            anchor="start",
            line_cls="belongs-line",
            label_cls="belongs-label",
        )
    )
    if ci_high > ci_low:
        parts.append(
            S.text(
                x1,
                LABEL_Y + 16,
                f"shaded: 95% interval {S.fmt(ci_low)}–{S.fmt(ci_high)}",
                anchor="end",
                size=12,
                cls="note",
                halo=True,
            )
        )
    parts.append(S.svg_close())
    return "".join(parts)


# --------------------------------------------------------------------------------------
# The page
# --------------------------------------------------------------------------------------
CSS = """\
* { box-sizing: border-box; }
/* The report's palette, one step smaller: warm paper, three inks, two hairlines, and two semantic
   hues -- blue for the line the cost minimum points at, vermilion for the line in use and for a
   failing gate. Text in either hue wears its darker -ink step so it clears 4.5:1. */
:root {
  color-scheme: light dark;
  --bg: #f7f6f2; --panel: #ffffff; --panel-alt: #f0eee8;
  --ink: #1b1a17; --ink-2: #3f3d38; --muted: #6f6b63; --rule: #e4e0d8; --rule-strong: #cfcac0;
  --accent: #1f5fbf; --accent-ink: #1a4f9e; --accent-soft: #e9f0fa;
  --alert: #d1491f; --alert-ink: #ad3a14; --good: #1d7a4b;
  /* No web font: nothing is fetched. Numbers use the sans face with tabular figures; the mono
     face is for identifiers only. */
  --font: Inter, "SF Pro Text", -apple-system, BlinkMacSystemFont, "Segoe UI Variable Text",
    "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  --serif: "Iowan Old Style", Charter, "Bitstream Charter", "Sitka Heading", "Source Serif Pro",
    Cambria, Georgia, serif;
  --mono: "JetBrains Mono", "SF Mono", SFMono-Regular, ui-monospace, "Cascadia Mono",
    "Roboto Mono", Menlo, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark;
    --bg: #141412; --panel: #1b1b18; --panel-alt: #25241f;
    --ink: #eeece6; --ink-2: #cfccc3; --muted: #a19d93; --rule: #2e2d28; --rule-strong: #45433c;
    --accent: #4f8be8; --accent-ink: #8fb6f5; --accent-soft: #1b2535;
    --alert: #e8683a; --alert-ink: #f59a74; --good: #5cc98f;
  }
}
html, body { margin: 0; background: var(--bg); color: var(--ink); }
body {
  font: 15px/1.5 var(--font); font-feature-settings: "cv11", "ss01";
  -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
}
main { max-width: 992px; margin: 0; padding: 18px 16px 16px; }

/* A technical report, not a landing page: a small kicker, the claim in the serif, a row of facts,
   then the evidence. Type size, weight and hairline rules carry the hierarchy. */
header p { margin: 0; }
.kicker { font-size: 12px; color: var(--muted); }
.kicker .synthetic { color: var(--ink-2); font-weight: 600; }
h1 {
  margin: 4px 0 0; font-family: var(--serif); font-size: 26px; line-height: 1.2;
  font-weight: 600; letter-spacing: -0.012em;
}
h1 .answer { font-variant-numeric: tabular-nums lining-nums; color: var(--accent-ink); }
h2 {
  margin: 12px 0 4px; padding-top: 8px; border-top: 1px solid var(--rule-strong);
  font-family: var(--serif); font-size: 17px; line-height: 1.3; font-weight: 600;
}
/* The facts row already closes the header with a hairline; a second rule under it is noise. */
header + h2 { margin-top: 10px; padding-top: 0; border-top: 0; }
.facts {
  display: flex; flex-wrap: wrap; gap: 4px 0; margin-top: 8px; padding: 6px 0;
  border-top: 1px solid var(--rule); border-bottom: 1px solid var(--rule);
  font-size: 13px; color: var(--muted);
}
.facts span.fact { padding-right: 12px; margin-right: 12px; border-right: 1px solid var(--rule); }
.facts span.fact:last-child { border-right: 0; margin-right: 0; padding-right: 0; }
.v { font-variant-numeric: tabular-nums lining-nums; color: var(--ink); font-weight: 600; }
.v.belongs { color: var(--accent-ink); }
code {
  font-family: var(--mono); font-size: 0.86em; color: var(--ink-2);
  background: var(--panel-alt); border-radius: 3px; padding: 1px 5px;
}

/* The status badge carries the word, with a stroke; readable in greyscale, never colour alone. */
.badge {
  display: inline-block; font: 600 11px/1.45 var(--font); letter-spacing: .04em;
  padding: 0 6px; border: 1px solid currentColor; border-radius: 3px; vertical-align: 1px;
}
.badge.fail { color: var(--alert-ink); }
.badge.pass { color: var(--good); }

/* Text reads left, numbers right in tabular figures; a heavier rule under the header, hairlines
   between rows. The column the page argues for is the one with a ground. */
table { width: 100%; border-collapse: collapse; margin: 2px 0 0; font-size: 14px; }
th, td { text-align: left; padding: 4px 12px; border-bottom: 1px solid var(--rule); vertical-align: top; line-height: 1.4; }
th:first-child, td:first-child { padding-left: 0; }
thead th {
  font-size: 12px; font-weight: 600; color: var(--muted); white-space: nowrap;
  border-bottom: 1px solid var(--rule-strong); padding-top: 2px;
}
td.num, th.num { text-align: right; white-space: nowrap; }
td.num { font-variant-numeric: tabular-nums lining-nums; }
td:first-child { color: var(--ink-2); }
td.was { color: var(--muted); }
table.impact th:nth-child(3), table.impact td:nth-child(3) { background: var(--accent-soft); }
table.impact thead th:nth-child(3) { color: var(--accent-ink); box-shadow: inset 0 2px 0 var(--accent); }
td.now { font-weight: 600; }
tbody tr:last-child td { border-bottom: 0; }

figure { margin: 0; }
figure svg { display: block; width: 100%; height: auto; }
figcaption { font-size: 12px; line-height: 1.5; color: var(--muted); }
svg text { font-variant-numeric: tabular-nums; }

/* Chart colours are classes, so the chart follows prefers-color-scheme like the page does. */
.grid { stroke: var(--rule); stroke-width: 1; }
.axis { stroke: var(--ink-2); stroke-width: 1; }
.baseline { stroke: var(--rule-strong); stroke-width: 1; }
text.tick, text.note { fill: var(--muted); }
text.label { fill: var(--ink); }
.halo { paint-order: stroke; stroke: var(--bg); stroke-width: 4px; stroke-linejoin: round; }
.curve { fill: none; stroke: var(--ink); stroke-width: 2; }
.ci-band { fill: var(--accent); opacity: .10; }
.dist { fill: var(--muted); opacity: .38; }
.min-dot { fill: var(--accent); stroke: var(--bg); stroke-width: 2px; }
.inuse-dot { fill: var(--alert); stroke: var(--bg); stroke-width: 2px; }
.inuse-line { stroke: var(--alert); stroke-width: 1.6; }
.belongs-line { stroke: var(--accent); stroke-width: 2; }
text.inuse-label { fill: var(--alert-ink); }
text.belongs-label { fill: var(--accent-ink); }
text.inuse-value { fill: var(--alert-ink); }
text.belongs-value { fill: var(--accent-ink); }

details { border-bottom: 1px solid var(--rule); }
details > summary {
  cursor: pointer; padding: 6px 0; font-size: 13px; color: var(--ink-2); list-style: none;
}
details > summary:hover { color: var(--ink); }
details > summary::-webkit-details-marker { display: none; }
details > summary::before {
  content: ""; display: inline-block; vertical-align: 2px; width: 6px; height: 6px;
  margin: 0 10px 0 2px;
  border-right: 1.5px solid var(--muted); border-bottom: 1.5px solid var(--muted);
  transform: rotate(-45deg);
}
details[open] > summary::before { transform: rotate(45deg); }
details .body { padding: 2px 0 10px; font-size: 13px; color: var(--ink-2); }
details .body p { margin: 0 0 4px; max-width: 90ch; }
.fail-text { color: var(--alert-ink); font-weight: 600; }

@media (max-width: 900px) {
  table { display: block; max-width: 100%; overflow-x: auto; }
}
@media print {
  main { max-width: none; padding: 0; }
  details { display: block; }
}
"""


def _impact_table(impact: ImpactTable) -> str:
    head = (
        '<tr><th>what changes</th><th class="num">line in use</th>'
        '<th class="num">line at the cost minimum</th><th class="num">change</th></tr>'
    )
    rows = "".join(
        f'<tr><td>{S.escape(row.label)}</td><td class="num was">{S.escape(row.current)}</td>'
        f'<td class="num now">{S.escape(row.recommended)}</td>'
        f'<td class="num">{S.escape(row.change)}</td></tr>'
        for row in impact.rows
    )
    return f'<table class="impact"><thead>{head}</thead><tbody>{rows}</tbody></table>'


def _facts(screen: Screen) -> str:
    """The row that answers the first questions before any table does: which line, which gate."""
    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    result = screen.result
    gate = (
        '<span class="badge fail">FAIL</span>'
        if screen.failures
        else '<span class="badge pass">PASS</span>'
    )
    facts = (
        f"drift gate {gate}",
        f'line in use <span class="v">{S.escape(S.fmt(current))}</span>',
        f'cost minimum <span class="v belongs">{S.escape(S.fmt(result.threshold))}</span>'
        f' (95% <span class="v">{S.escape(S.fmt(result.ci_low))}–'
        f"{S.escape(S.fmt(result.ci_high))}</span>)",
        f'<span class="v">{screen.metrics.n:,}</span> labeled decisions of '
        f"<code>{S.escape(screen.question)}</code>",
        f"action <code>{S.escape(screen.question_label)}</code>",
        f'<span class="v">{len(screen.dataset.questions)}</span> questions',
    )
    return '<p class="facts">' + "".join(f'<span class="fact">{f}</span>' for f in facts) + "</p>"


def _details(screen: Screen) -> str:
    """The secondary evidence, one click away: what cost counts, and the drift caveat.

    A threshold measured on a model that is drifting is a number with an expiry date, so the failing
    gate is stated in full here as well as flagged at the top.
    """
    result = screen.result
    costs = (
        f"Cost counts an auto-accept miss at {format_amount(result.cost_false_accept, CURRENCY)} "
        f"and a review at {format_amount(result.cost_escalate, CURRENCY)}, from a synthetic cost "
        f"matrix. The minimum is {format_amount(result.expected_cost_per_case, CURRENCY)} per "
        "case; the 95% bootstrap "
        f"interval on where it sits is {S.fmt(result.ci_low)}–{S.fmt(result.ci_high)}, "
        f"n={result.n_records:,}. Everything on this page is synthetic."
    )
    failure = screen.failures[0] if screen.failures else None
    gate = (
        f'<span class="fail-text">This log fails the drift gate: {S.escape(failure.check)} '
        f"+{S.fmt(failure.value, 3)} over the {S.fmt(failure.limit, 3)} limit</span> "
        f"({S.escape(failure.detail)}). A threshold measured on a model that is changing has an "
        "expiry date; move the line, and re-measure after the next model version ships."
        if failure is not None
        else "This log passes the drift gate."
    )
    return (
        "<details><summary>How cost is counted, and the interval on the recommendation</summary>"
        f'<div class="body"><p>{S.escape(costs)}</p></div></details>'
        "<details><summary>Why the drift gate "
        f"{'fails' if failure is not None else 'passes'} on the same log</summary>"
        f'<div class="body"><p>{gate}</p></div></details>'
    )


def kicker_line(*, provenance: str, models: str, product: str = "jeval") -> str:
    """The one line above the claim: what log this is, how big, in what currency, which models."""
    return (
        f'<p class="kicker">{S.escape(product)} · <span class="synthetic">synthetic log</span> · '
        f"{S.escape(provenance)} · {S.escape(models)}</p>"
    )


def render_body(screen: Screen, *, kicker: str) -> str:
    """Everything inside ``<main>``: a claim, a row of facts, the chart, the impact table, the small
    print. ``kicker`` is the markup placed above the claim, or empty when a host page supplies its own
    line, as ``examples/make-workbench.py`` does; nothing else on the screen changes with the host."""
    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    belongs = screen.result.threshold
    claim = (
        f'The line belongs at <span class="answer">{S.escape(S.fmt(belongs))}</span>, '
        f"not {S.escape(S.fmt(current))}."
        if belongs != current
        else f"The line in use, {S.escape(S.fmt(current))}, is where the cost minimum is."
    )
    delta = next(
        (row.change for row in screen.impact.rows if row.label.startswith("cost per case")), ""
    )
    # A cost curve whose axis starts at its own minimum is the standard way to make a small effect
    # look like a cliff, so the chart says so in words. Both numbers come from the curve itself.
    costs = [p.expected_cost for p in screen.result.curve if p.expected_cost == p.expected_cost]
    zoom_note = (
        f"The vertical axis is truncated near {format_amount(min(costs), screen.impact.currency)} "
        "instead of zero, so the drop "
        f"looks larger than it is: the whole effect is {delta} on cost per case."
        if costs and delta
        else ""
    )
    return (
        f"<header>{kicker}"
        f"<h1>{claim}</h1>"
        f"{_facts(screen)}</header>"
        "<h2>Cost per case against the threshold</h2>"
        f"<figure>{_chart(screen)}"
        "<figcaption>The threshold is how sure the model has to be before it answers alone; both "
        "lines are drawn where they stand. The shaded band is the 95% interval on the "
        "recommendation. The bars underneath are the confidence distribution: they are what moves "
        f"when the line moves. {S.escape(zoom_note)}</figcaption></figure>"
        f"<h2>What moving the line buys{S.escape(' · cost per case ' + delta) if delta else ''}"
        "</h2>"
        f"{_impact_table(screen.impact)}"
        f"{_details(screen)}"
    )


def render_screen(screen: Screen, *, provenance: str, models: str) -> str:
    """The whole page: the document shell around ``render_body``."""
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>jeval · {S.escape(screen.question)} · where the line belongs</title>"
        f"<style>{CSS}</style></head><body><main>"
        f"{render_body(screen, kicker=kicker_line(provenance=provenance, models=models))}"
        "</main></body></html>\n"
    )


def build_screen() -> tuple[Screen, str, str]:
    """The analysis behind the page, plus the two strings the kicker states about it.

    Shared with ``examples/make-workbench.py``, which frames the same screen inside a longer page.
    """
    serving, candidate = build_records()
    # The cost matrix lives in this file, not beside the artefact: the script is the provenance, and
    # a stray YAML in examples/ would look like a runnable project instead of one demo's inputs.
    with tempfile.TemporaryDirectory(prefix="jeval-dashboard-") as work:
        costs_path = Path(work) / "costs.yaml"
        costs_path.write_text(COSTS_YAML, encoding="utf-8")
        screen = analyse(serving, candidate, costs_path)
    models = sorted({record.model for record in [*serving, *candidate]})
    provenance = (
        f"{len(serving):,} decisions in production ({screen.dataset.n_labeled_gold:,} labeled) · "
        f"{CURRENCY} at {MONTHLY_VOLUME:,.0f} cases a month"
    )
    models_text = "models " + ", ".join(models)
    return screen, provenance, models_text


def build_document() -> tuple[str, Screen]:
    """The whole page, plus the analysis behind it.

    ``main`` writes what this returns, and ``tests/test_demo_dashboard.py`` rebuilds it to keep the
    committed artefact honest: the build is deterministic -- seeded synthesis, no clock in the
    document -- so that check can be an equality rather than a property.
    """
    screen, provenance, models_text = build_screen()
    return render_screen(screen, provenance=provenance, models=models_text), screen


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else Path("examples/demo-dashboard.html")
    html, screen = build_document()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(html.encode('utf-8')) // 1024} KB)")
    print(
        f"line in use {S.fmt(screen.impact.current_threshold)}, "
        f"where it belongs {S.fmt(screen.result.threshold)}"
    )
    for failure in screen.failures:
        print(f"drift failure: {failure.check} {failure.detail}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
