"""Build the one-screen dashboard used for the walkthrough recording.

This is not a jeval command and not a product surface: the product writes one report, and a
dashboard is explicitly out of scope. This is a *presentation* of the same analysis, computed by the
same library, arranged so that one screen makes one argument -- the line in use is in the wrong
place, here is where it belongs, here is what moving it buys.

    uv run python examples/make-demo-dashboard.py examples/demo-dashboard.html

One file, no server, no network, no chart library, no JavaScript. Every figure is computed by the
library the report uses (``evaluate``, ``sweep_actions``, ``build_impact``), and nothing on the page
is typed in by hand, which is what makes it safe to put on screen.

The synthetic log is two model versions of the same four questions. The older version is roughly
honest on the question the cost matrix fires on; the newer one is degraded, which is the change the
drift check exists to catch.
"""

from __future__ import annotations

import sys
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jeval.cli import resolve_cost_actions, sweep_actions
from jeval.drift import parse_fail_on, run_checks
from jeval.evaluate import DatasetReport, evaluate
from jeval.report import svg as S
from jeval.report.model import ImpactTable, ThresholdResult
from jeval.schema import DecisionRecord
from jeval.synth import SynthSpec, demo_dataset, generate

NEWER_START = datetime(2026, 9, 17, tzinfo=timezone.utc)

CURRENCY = "KRW"
MONTHLY_VOLUME = 20_000.0
CURRENT_THRESHOLD = 0.60
FAIL_ON = "ece-increase=0.05"

# The cost matrix the dashboard runs on -- the same synthetic one `jeval demo` writes, so the numbers
# on the screen can be checked against `examples/report-example.html` in this repository.
COSTS_YAML = """\
# SYNTHETIC cost figures. Replace them with your own before believing any threshold that comes
# out of this file.
actions:
  - name: auto_refund
    question: intent
    when: refund_request
    cost_false_accept: 12000
    cost_escalate: 2000
    cost_false_reject: 0
  - name: auto_route
    question: department
    when: billing
    cost_false_accept: 8000
    cost_escalate: 1500
    cost_false_reject: 200
  - name: auto_escalate_urgent
    question: is_urgent
    when: "yes"
    cost_false_accept: 30000
    cost_escalate: 500
    cost_false_reject: 1000
"""

# The chart's own geometry. The viewBox is deliberately wider than a laptop window: the SVG scales
# down to the column, so a 13px label is drawn as 13px instead of shrinking to 10px.
CHART_W = 1120.0
CHART_H = 340.0
PLOT_LEFT = 78.0
PLOT_RIGHT = 30.0
PLOT_TOP = 34.0
PLOT_BOTTOM = 116.0
STRIP_GAP = 22.0
STRIP_H = 38.0
LABEL_Y = 22.0
X_TICK_Y = 304.0
X_TITLE_Y = 325.0
Y_TITLE_X = 20.0


@dataclass
class Screen:
    """Everything the one screen shows, computed once."""

    dataset: DatasetReport
    result: ThresholdResult
    impact: ImpactTable
    metrics: Any
    failures: list[Any]
    question: str
    question_label: str


def build_records() -> tuple[list[DecisionRecord], list[DecisionRecord]]:
    """The version in production, and the candidate that has to be judged against it.

    The production half is `jeval demo`'s own log at the same seed, so the numbers on the screen can
    be checked against the committed report in this repository. The candidate is the same four
    questions generated by a degraded model: overconfident on the question the cost matrix fires on,
    which is the change the drift check exists to catch.
    """
    serving = list(demo_dataset(seed=11, scale=0.5).records)
    degraded = (
        SynthSpec(
            n=310,
            mode="overconfident",
            exponent=0.35,
            question_key="department",
            model="jev-1.14.0",
            start=NEWER_START,
            seed=21,
            languages=("ko", "en"),
            tiers=("free", "pro"),
            label_fraction=0.86,
        ),
        SynthSpec(
            n=270,
            mode="inflated",
            inflation=1.3,
            question_key="intent",
            classes=("refund_request", "check_balance", "other"),
            model="jev-1.14.0",
            start=NEWER_START,
            seed=22,
            languages=("ko", "en"),
            label_fraction=0.9,
        ),
        SynthSpec(
            n=215,
            mode="calibrated",
            question_key="is_urgent",
            question_type="noul",
            model="jev-1.14.0",
            start=NEWER_START,
            seed=23,
            languages=("ko", "en"),
            label_fraction=0.88,
        ),
        SynthSpec(
            n=110,
            mode="inflated",
            question_key="satisfaction",
            question_type="score",
            score_bias=0.18,
            model="jev-1.14.0",
            start=NEWER_START,
            seed=24,
            languages=("ko", "en"),
            label_fraction=0.8,
        ),
    )
    candidate = [record for spec in degraded for record in generate(spec)]
    return serving, candidate


def analyse(
    serving: Sequence[DecisionRecord], candidate: Sequence[DecisionRecord], costs_path: Path
) -> Screen:
    """Run the analysis the report runs, and keep the pieces one screen needs.

    The screen measures the version in production: a rollout decision is "here is what is live, here
    is what is proposed", and mixing the candidate into the reliability numbers would hide which of
    the two is miscalibrated. The candidate appears once, as the drift check's failure.
    """
    records = list(serving)
    dataset = evaluate(records, n_bins=10, alpha=0.05, n_boot=200, by=("lang", "tier"))
    actions, _note = resolve_cost_actions(costs_path, costs_path.parent)
    thresholds, impacts = sweep_actions(
        actions,
        records,
        n_boot=200,
        alpha=0.05,
        monthly_volume=MONTHLY_VOLUME,
        currency=CURRENCY,
        current_threshold=CURRENT_THRESHOLD,
    )
    result = next((item for item in thresholds if item.curve), None)
    assert result is not None, "the demo cost matrix must produce a sweep"
    question = next(
        (item for item in dataset.questions if item.question_key == result.question), None
    )
    metrics = question.metrics if question is not None else dataset.overall
    drift = _drift_view([*records, *candidate])
    failures = list(run_checks(drift, parse_fail_on((FAIL_ON,)))) if drift is not None else []
    return Screen(
        dataset=dataset,
        result=result,
        impact=impacts[result.action],
        metrics=metrics,
        failures=failures,
        question=result.question,
        question_label=result.action,
    )


def _drift_view(records: Sequence[DecisionRecord], *, min_slice: int = 30) -> Any:
    """Compare model versions when the log holds more than one."""
    if len({record.model for record in records}) < 2:
        return None
    from jeval import drift as drift_engine

    return drift_engine.compare(records, min_slice=min_slice, alpha=0.05, n_boot=200)


# --------------------------------------------------------------------------------------
# The chart
# --------------------------------------------------------------------------------------
# Drawn here rather than taken from `jeval.report.charts`, because this chart has to do something the
# report's does not: put both thresholds on one axis, label them where they stand, and show the
# confidence distribution underneath, so the reader can see what moves when the line moves.
# Colours come from CSS classes rather than attributes, so the chart follows the colour scheme.
def _threshold_line(
    x: float,
    *,
    y0: float,
    y1: float,
    label: str,
    anchor: str,
    line_cls: str,
    label_cls: str,
    dash: str = "",
) -> str:
    """A vertical line where a threshold sits, labelled where it sits.

    Both lines on this chart are labelled in words as well as drawn in different colours and dash
    patterns: a reader who cannot tell the colours apart still gets the whole argument.
    """
    return "".join(
        (
            S.line(x, y0, x, y1, dash=dash, cls=line_cls),
            S.text(
                x + (-10 if anchor == "end" else 10),
                LABEL_Y,
                label,
                anchor=anchor,
                size=13.5,
                weight=650,
                cls=label_cls,
                halo=True,
            ),
        )
    )


def _chart(screen: Screen) -> str:
    points = [point for point in screen.result.curve if point.expected_cost == point.expected_cost]
    assert points, "the sweep must produce points"
    costs = [point.expected_cost for point in points]
    lo, hi = min(costs), max(costs)
    pad = max(1e-9, (hi - lo) * 0.16)
    y_lo, y_hi = max(0.0, lo - pad), hi + pad

    x0, x1 = PLOT_LEFT, CHART_W - PLOT_RIGHT
    y_top = PLOT_TOP
    y_bottom = CHART_H - PLOT_BOTTOM
    strip_top = y_bottom + STRIP_GAP
    strip_bottom = strip_top + STRIP_H

    def px(threshold: float) -> float:
        return x0 + threshold * (x1 - x0)

    def py(cost: float) -> float:
        return y_bottom - (cost - y_lo) / max(1e-12, y_hi - y_lo) * (y_bottom - y_top)

    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    belongs = screen.result.threshold
    per_case = screen.result.expected_cost_per_case

    parts = [
        S.svg_open(
            CHART_W,
            CHART_H,
            title=(
                "Expected cost per case against the threshold, with the line in use and the line "
                "the cost minimum points at"
            ),
            desc=(
                f"Cost per case is lowest at threshold {S.fmt(belongs)}, where it is "
                f"{S.money(per_case)}, and higher at the {S.fmt(current)} currently in use. The "
                "bars below the curve show how many decisions sit in each confidence range."
            ),
            cls="hero",
        )
    ]

    # The band between the two lines: the region the move covers.
    if belongs != current:
        left, right = sorted((px(current), px(belongs)))
        parts.append(
            S.rect(
                left, y_top, right - left, y_bottom - y_top, cls="move-band", extra='stroke="none"'
            )
        )

    # The bootstrap interval on the threshold, drawn and not only printed: a point estimate quoted
    # over a wide interval is the easiest thing on this page to over-read.
    ci_low, ci_high = screen.result.ci_low, screen.result.ci_high
    if ci_high > ci_low:
        parts.append(
            S.rect(
                px(ci_low),
                y_top,
                px(ci_high) - px(ci_low),
                y_bottom - y_top,
                cls="ci-band",
                extra='stroke="none"',
            )
        )

    for value in S.nice_ticks(y_lo, y_hi, target=4):
        y = py(value)
        parts.append(S.line(x0, y, x1, y, cls="grid"))
        parts.append(
            S.text(x0 - 12, y + 4.5, S.money(value), anchor="end", size=13, mono=True, cls="tick")
        )
    for value in (0.0, 0.25, 0.5, 0.75, 1.0):
        x = px(value)
        parts.append(S.line(x, y_top, x, strip_bottom, cls="grid", opacity=0.75))
        parts.append(
            S.text(x, X_TICK_Y, S.fmt(value), anchor="middle", size=13, mono=True, cls="tick")
        )
    parts.append(S.line(x0, y_bottom, x1, y_bottom, cls="axis"))
    parts.append(S.line(x0, y_top, x0, y_bottom, cls="axis"))
    parts.append(S.line(x0, strip_bottom, x1, strip_bottom, cls="axis"))
    parts.append(
        S.text(
            (x0 + x1) / 2.0,
            X_TITLE_Y,
            "threshold: how sure the model has to be before it answers alone",
            anchor="middle",
            size=13.5,
            cls="label",
        )
    )
    if ci_high > ci_low:
        parts.append(
            S.text(
                x0,
                CHART_H - 4,
                f"the band is the 95% interval on where the line belongs: {S.fmt(ci_low)}–"
                f"{S.fmt(ci_high)}",
                size=12.5,
                cls="label",
            )
        )
    parts.append(
        S.text(
            Y_TITLE_X,
            (y_top + y_bottom) / 2.0,
            f"cost per case ({CURRENCY})",
            anchor="middle",
            size=13.5,
            cls="label",
            rotate=-90,
            rotate_at=(Y_TITLE_X, (y_top + y_bottom) / 2.0),
        )
    )

    # The distribution under the curve: how many decisions sit in each confidence band.
    buckets = list(screen.metrics.confidence_buckets)
    if buckets:
        peak = max(count for _lo, _hi, count in buckets) or 1
        for band_lo, band_hi, count in buckets:
            left = px(band_lo) + 1.5
            width = max(1.5, px(band_hi) - px(band_lo) - 3.0)
            height = max(1.5, (count / peak) * STRIP_H)
            parts.append(
                S.rect(
                    left,
                    strip_bottom - height,
                    width,
                    height,
                    cls="dist",
                    rx=2.0,
                    extra='stroke="none"',
                )
            )
        parts.append(
            S.text(
                x0,
                strip_top - 11,
                f"{screen.metrics.n:,} labeled decisions in these bands",
                size=13,
                cls="label",
            )
        )

    parts.append(
        S.polyline(
            [(px(point.threshold), py(point.expected_cost)) for point in points],
            cls="curve",
            smooth=True,
        )
    )
    parts.append(
        S.dot(
            px(belongs),
            py(per_case),
            5.5,
            cls="min-dot",
            tooltip=f"cost minimum at {S.fmt(belongs)}",
            extra='stroke="none"',
        )
    )
    parts.append(
        _threshold_line(
            px(current),
            y0=y_top,
            y1=y_bottom,
            label=f"in use {S.fmt(current)}",
            anchor="end",
            line_cls="inuse-line",
            label_cls="inuse-label",
            dash="6 4",
        )
    )
    parts.append(
        _threshold_line(
            px(belongs),
            y0=y_top,
            y1=strip_bottom,
            label=f"where it belongs {S.fmt(belongs)}",
            anchor="start",
            line_cls="belongs-line",
            label_cls="belongs-label",
        )
    )
    parts.append(S.svg_close())
    return "".join(parts)


# --------------------------------------------------------------------------------------
# The page
# --------------------------------------------------------------------------------------
CSS = """\
* { box-sizing: border-box; }
:root {
  --bg: #ffffff; --ink: #111418; --muted: #5f6773; --rule: #e3e7ed;
  --accent: #1f5fd0; --accent-soft: rgba(31,95,208,.09);
  --inuse: #96660a; --inuse-soft: rgba(150,102,10,.11);
  --bad: #b3261e; --grid: #eceef3; --dist: #a9b1bf;
  --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0c0e12; --ink: #eef1f6; --muted: #9ba5b3; --rule: #262b33;
    --accent: #6aa9ff; --accent-soft: rgba(106,169,255,.14);
    --inuse: #e3a63c; --inuse-soft: rgba(227,166,60,.14);
    --bad: #ff9187; --grid: #20242b; --dist: #4c545f;
  }
}
html, body { margin: 0; background: var(--bg); color: var(--ink); }
body {
  font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Inter, sans-serif;
  -webkit-font-smoothing: antialiased;
}
main { max-width: 1180px; margin: 0 auto; padding: 18px 28px 11px; }

/* One eyebrow, one claim, one line of body, then the evidence -- five clearly different sizes,
   because every element at 15px is what makes a page unreadable. */
.masthead { display: flex; align-items: baseline; gap: 8px 12px; flex-wrap: wrap; font-size: 12.5px; color: var(--muted); }
.masthead .brand { font-size: 15px; font-weight: 700; letter-spacing: -0.02em; color: var(--ink); }
.masthead .sep { color: var(--rule); }

.claim h1 { margin: 12px 0 0; font-size: 29px; line-height: 1.16; letter-spacing: -0.022em; font-weight: 650; }
.claim h1 em { font-style: normal; color: var(--accent); }
.claim p { margin: 7px 0 0; font-size: 15px; color: var(--muted); max-width: 64ch; }

.row { display: grid; grid-template-columns: 290px minmax(0, 1fr); gap: 26px; margin-top: 18px; align-items: start; }

.answer { border: 1px solid var(--accent); background: var(--accent-soft); border-radius: 12px; padding: 13px 16px 12px; }
.eyebrow { font-size: 11.5px; font-weight: 650; letter-spacing: .08em; text-transform: uppercase; color: var(--accent); }
.answer .big { font-family: var(--mono); font-size: 46px; line-height: 1.02; font-weight: 600; letter-spacing: -0.03em; margin: 4px 0 3px; color: var(--accent); }
.answer .cost { font-family: var(--mono); font-size: 15.5px; font-weight: 600; }
.answer .ci { font-family: var(--mono); font-size: 12.5px; color: var(--muted); margin-top: 3px; }
.answer .now { margin-top: 11px; padding-top: 10px; border-top: 1px solid var(--rule); display: flex; align-items: baseline; gap: 8px; }
.answer .now .chip { font-family: var(--mono); font-size: 15px; font-weight: 600; color: var(--inuse); background: var(--inuse-soft); border-radius: 6px; padding: 2px 8px; }
.answer .now .what { font-size: 12.5px; color: var(--muted); }

table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid var(--rule); font-size: 13.5px; }
th { font-size: 11.5px; text-transform: uppercase; letter-spacing: .07em; color: var(--muted); font-weight: 650; padding-top: 0; }
td.num, th.num { text-align: right; font-family: var(--mono); font-variant-numeric: tabular-nums; }
tbody tr:last-child td { border-bottom: 0; }
td.was { color: var(--muted); }
td.now { color: var(--accent); font-weight: 600; }
td.delta { color: var(--ink); }
code { font-family: var(--mono); font-size: .93em; }

figure { margin: 12px 0 0; }
figure svg { display: block; width: 100%; height: auto; }
figcaption { margin-top: 5px; font-size: 12.5px; color: var(--muted); }

/* Chart colours are classes, so the chart follows prefers-color-scheme like the page does. */
.grid { stroke: var(--grid); stroke-width: 1; }
.axis { stroke: var(--rule); stroke-width: 1.2; }
text.tick { fill: var(--muted); }
text.label { fill: var(--muted); }
.curve { fill: none; stroke: var(--ink); stroke-width: 2.6; }
.move-band { fill: var(--accent); opacity: .07; }
.ci-band { fill: var(--accent); opacity: .06; }
.dist { fill: var(--dist); }
.min-dot { fill: var(--accent); stroke: none; }
.inuse-line { stroke: var(--inuse); stroke-width: 2; }
.belongs-line { stroke: var(--accent); stroke-width: 2.6; }
text.inuse-label { fill: var(--inuse); }
text.belongs-label { fill: var(--accent); }

footer { margin-top: 12px; padding-top: 9px; border-top: 1px solid var(--rule); display: flex; flex-wrap: wrap; gap: 4px 18px; font-size: 12.5px; color: var(--muted); }
footer .fail { color: var(--bad); font-weight: 600; }
footer .pass { color: var(--muted); }

@media (max-width: 900px) {
  main { padding: 18px 16px 14px; }
  .row { grid-template-columns: 1fr; gap: 16px; }
  .claim h1 { font-size: 26px; }
  .answer .big { font-size: 42px; }
  table { display: block; max-width: 100%; overflow-x: auto; }
}
/* A short window loses the page's breathing room before it loses the chart: a 13" laptop at its
   default resolution is 1280x800, which is 100px less than the layout wants. */
@media (max-height: 860px) {
  main { padding: 12px 28px 8px; }
  .claim h1 { font-size: 26px; }
  .claim p { font-size: 14px; margin-top: 6px; }
  .row { margin-top: 14px; }
  .answer .big { font-size: 40px; }
  footer { margin-top: 9px; padding-top: 7px; }
}
@media print {
  main { max-width: none; padding: 0; }
  .answer { background: none; }
}
"""


def _answer(screen: Screen) -> str:
    belongs = screen.result.threshold
    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    delta = next(
        (row.change for row in screen.impact.rows if row.label.startswith("cost per case")), ""
    )
    return (
        '<div class="answer">'
        '<div class="eyebrow">where the line belongs</div>'
        f'<div class="big">{S.escape(S.fmt(belongs))}</div>'
        f'<div class="cost">{S.escape(screen.impact.currency)} '
        f"{screen.result.expected_cost_per_case:,.2f} per case"
        f"{S.escape(' · ' + delta) if delta else ''}</div>"
        f'<div class="ci">95% CI {S.escape(S.fmt(screen.result.ci_low))}–'
        f"{S.escape(S.fmt(screen.result.ci_high))} · n={screen.result.n_records:,}</div>"
        f'<div class="now"><span class="chip">in use {S.escape(S.fmt(current))}</span>'
        '<span class="what">which is not where the cost minimum is</span></div>'
        "</div>"
    )


def _impact_table(impact: ImpactTable) -> str:
    head = (
        '<tr><th>metric</th><th class="num">in use</th>'
        '<th class="num">at the minimum</th><th class="num">change</th></tr>'
    )
    rows = "".join(
        f'<tr><td>{S.escape(row.label)}</td><td class="num was">{S.escape(row.current)}</td>'
        f'<td class="num now">{S.escape(row.recommended)}</td>'
        f'<td class="num delta">{S.escape(row.change)}</td></tr>'
        for row in impact.rows
    )
    return f'<table class="impact"><thead>{head}</thead><tbody>{rows}</tbody></table>'


def _footer(screen: Screen, provenance: str) -> str:
    """The small print, including the two things a reader would otherwise have to guess.

    What "cost" counts, from the cost matrix itself, and the caveat that the same log's drift gate
    fails: a threshold measured on a model that is drifting is a number with an expiry date.
    """
    result = screen.result
    costs = (
        f"cost: an auto-accept miss at {CURRENCY} {result.cost_false_accept:,.0f}, a review at "
        f"{CURRENCY} {result.cost_escalate:,.0f} (synthetic matrix)"
    )
    failure = screen.failures[0] if screen.failures else None
    gate = (
        f'<span class="fail">caveat: this log fails the drift gate · {S.escape(failure.check)} '
        f"+{S.fmt(failure.value, 3)} over the {S.fmt(failure.limit, 3)} limit</span>"
        if failure is not None
        else '<span class="pass">this log passes the drift gate</span>'
    )
    return (
        f"<footer><span>{S.escape(provenance)}</span><span>{S.escape(costs)}</span>{gate}</footer>"
    )


def render_screen(screen: Screen, *, provenance: str) -> str:
    """The whole page: one claim, one answer, one chart, one table."""
    current = screen.impact.current_threshold or CURRENT_THRESHOLD
    belongs = screen.result.threshold
    claim = (
        f"The line belongs at <em>{S.escape(S.fmt(belongs))}</em>, not {S.escape(S.fmt(current))}."
        if belongs != current
        else f"The line in use, {S.escape(S.fmt(current))}, is where the cost minimum is."
    )
    return (
        "<!doctype html>\n"
        '<html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f"<title>jeval · {S.escape(screen.question)} · where the line belongs</title>"
        f"<style>{CSS}</style></head><body><main>"
        '<div class="masthead"><span class="brand">jeval</span><span class="sep">·</span>'
        f"<span>{S.escape(provenance)}</span></div>"
        f'<div class="claim"><h1>{claim}</h1>'
        "<p>One number decides whether a case is handled by the model or by a person. This is that "
        f"number for <code>{S.escape(screen.question_label)}</code>, measured on the "
        f"{screen.metrics.n:,} labeled decisions of its question.</p></div>"
        f'<div class="row">{_answer(screen)}{_impact_table(screen.impact)}</div>'
        f"<figure>{_chart(screen)}"
        "<figcaption>Cost per case against the threshold, with both lines drawn where they stand. "
        "The bars underneath are the confidence distribution: they are what moves when the line "
        "moves.</figcaption></figure>"
        f"{_footer(screen, provenance)}"
        "</main></body></html>\n"
    )


def build_document() -> tuple[str, Screen]:
    """The whole page, plus the analysis behind it.

    ``main`` writes what this returns, and ``tests/test_demo_dashboard.py`` rebuilds it to keep the
    committed artefact honest: the build is deterministic -- seeded synthesis, no clock in the
    document -- so that check can be an equality rather than a property.
    """
    serving, candidate = build_records()
    # The cost matrix lives in this file, not beside the artefact: the script is the provenance, and
    # a stray YAML in examples/ would look like a runnable project instead of one demo's inputs.
    with tempfile.TemporaryDirectory(prefix="jeval-dashboard-") as work:
        costs_path = Path(work) / "costs.yaml"
        costs_path.write_text(COSTS_YAML, encoding="utf-8")
        screen = analyse(serving, candidate, costs_path)
    models = sorted({record.model for record in [*serving, *candidate]})
    provenance = (
        f"synthetic log · {len(serving):,} decisions in production "
        f"({screen.dataset.n_labeled_gold:,} labeled) · {len(screen.dataset.questions)} questions · "
        f"{CURRENCY} at {MONTHLY_VOLUME:,.0f} cases a month · {models[-1]}"
    )
    return render_screen(screen, provenance=provenance), screen


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else Path("examples/demo-dashboard.html")
    html, screen = build_document()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(html.encode('utf-8')) // 1024} KB)")
    print(
        f"line in use {S.fmt(screen.impact.current_threshold)}, "
        f"where it belongs {S.fmt(screen.result.threshold)}"
    )
    for failure in screen.failures:
        print(f"drift failure: {failure.check} {failure.detail}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
